const PREFFIX = '@app';

export const GET_CITIES = `${PREFFIX}/GET_CITIES`;
export const GET_CITIES_START = `${PREFFIX}/GET_CITIES_START`;
export const GET_CITIES_SUCCESS = `${PREFFIX}/GET_CITIES_SUCCESS`;
export const GET_CITIES_ERROR = `${PREFFIX}/GET_CITIES_ERROR`;
export const GET_TEMPERATURE = `${PREFFIX}/GET_TEMPERATURE`;
export const GET_TEMPERATURE_START = `${PREFFIX}/GET_TEMPERATURE_START`;
export const GET_TEMPERATURE_SUCCESS = `${PREFFIX}/GET_TEMPERATURE_SUCCESS`;
export const GET_TEMPERATURE_ERROR = `${PREFFIX}/GET_TEMPERATURE_ERROR`;
export const GET_CURRENT_TEMP = `${PREFFIX}/GET_CURRENT_TEMP`;
